apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: scuba-video-dev-issuer
spec:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: azaz09112@naver.com
    privateKeySecretRef:
      name: scuba-video-dev-issuer
    solvers:
      - http01:
          ingress:
            class: traefik-cert-manager
