apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scuba-video-dev
metadata:
  name: scuba-video-dev
generatorOptions:
  disableNameSuffixHash: true
resources:
  - 00namespace.yaml
  - 01endpoint.yaml
  - 02service.yaml
  - 03issuer.yaml
  - 04certificate.yaml
  - 04ingressRouter.yaml
