apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scuba-video-certificate
  namespace: scuba-video
spec:
  secretName: scuba-video-crt-secret
  dnsNames:
    - video.scuba.deagwon.com
  issuerRef:
    name: scuba-video-issuer
    kind: Issuer