apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scuba-video
metadata:
  name: arbitrary
generatorOptions:
  disableNameSuffixHash: true
# generate secret only first time
secretGenerator:
  - name: scuba-video-regcred
    files:
      - .dockerconfigjson=01dockerconfig.json
    type: kubernetes.io/dockerconfigjson
  - name: scuba-video
    envs:
    - 01go.env
resources:
  - 00namespace.yaml
  - 02serviceAccount.yaml
  - 03deployment.yaml
  - 04service.yaml
  - 11issuer.yaml
  - 12certificate.yaml
  - 13middleWare.yaml
  - 14ingressRouter.yaml
  